version: "3.9"

services:
  db:
    image: postgres:15
    container_name: wonderfulmate_db
    restart: always
    environment:
      POSTGRES_DB: wonderfulmate
      POSTGRES_USER: wonderfulmate_user
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: wonderfulmate_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
